### ISSUE TITLE
Can you provide a browserify distribution?

### ISSUE THREAD

**Issue by hoogw** [mourner/rbush#102]
I have tried browserify, but run into error as
can you provide a browser version of it?
                           
                            browserify index.js --s rbush -o dist/rbush.js  

                            /Users/nicole/node/rbush/index.js:1
                           import quickselect from 'quickselect';
                          ^
                           ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by mourner** [comment]
There's already a browser version distributed, e.g. https://unpkg.com/rbush@3.0.1/rbush.js
