### ISSUE TITLE
Why "RTree" is geographically even distribution while "RBush" is NOT? 

### ISSUE THREAD

**Issue by hoogw** [mourner/rbush#106]
tree.search()
when I limit result count, I found it is not geographically distributed.  
it clustered, centralized as my another post screenshot shows
#103 

original "rtree" performs geographically distributed result, but rBush is NOT, why?

I use same testing data,   limit 500 out of 150k point.

I use original 'rtree' logic, I get even distribution of yellow circle point, with same dataset, 

when I use rbush, I got clustered, centralized, 

rTree ( good even distribution)

![image](https://user-images.githubusercontent.com/419582/81436937-28a2e800-911f-11ea-8875-77efe98ec483.png)

rbush ( centralized, not even,  )

![image](https://user-images.githubusercontent.com/419582/81437355-e0d09080-911f-11ea-9e06-81a1adc8ecbe.png)

How to make rBush like rTree output even distribution?
This is critical,  clustered map is not usable.

**Comment by mourner** [comment]
I don’t know, and I don’t think rbush should have a certain distribution in results. Please use rTree if it suites you better.
