### ISSUE TITLE
Does RBUSH supports to use Latitude and Longitude? 

### ISSUE THREAD

**Issue by raj1127** [mourner/rbush#111]
Can we use starting  latitude/longitude and ending latitude/longitude of the rectangle instead of minx, miny, maxx and maxy to insert and search rbush tree?

**Comment by mourner** [comment]
Yes.

**Comment by raj1127** [comment]
Thanks for your reply. Just one question what is then 

                        minX: (is it LEFT?)
                        minY: (is it TOP?)
                        maxX (is it RIGHT?)
                        maxY (is it BOTTOM?)

I will appreciate your reply.

**Comment by mourner** [comment]
In case of geographic locations, latitude goes from south to north, so minY is bottom and maxY is top. minX and maxX (longitude) are west and east respectively.

**Comment by raj1127** [comment]
Thanks Vladimir. I appreciate it.
