### ISSUE TITLE
non-root bbox

### ISSUE THREAD

**Issue by calvinmetcalf** [mourner/rbush#21]
it would be nice to have an easy way to tell rbush that it can find the bbox array somewhere besides the root, i.e. if you have an object that has it's bbox in item.bbox, maybe pass a 'string' to format instead of an array and have `_initFormat` do this for strings, can do a pull.

**Comment by mourner** [comment]
With the recent API change in 2.0, where bbox is no longer an array by default, I think we should keep format options as is.
