### ISSUE TITLE
search() based on item

### ISSUE THREAD

**Issue by TuurDutoit** [mourner/rbush#32]
Wouldn't it be more clear to have `rbush.search()` take an item (or an object formatted as one) instead of an array of AABB coordinates? This way, `search()` would take into account the second argument of the rbush constructor, which is more logical (I hunted for an issue for quite some time before I realized I had to pass an Array and not an item).
Also, creating an array for every search is not very memory efficient. I know we could reuse the same array, but that's a pain in the ass. So, as many people will search based on items (I think), having an item-based search is jutifiable.
Additionally, if you want both behaviours, why not have two methods (one for arrays, one for items)?

**Comment by mourner** [comment]
No, I don't think this is a good idea. Two methods is unnecessary complexity. Changing the API will be confusing to all people who validly expect `search` to get a bounding box for a query.
