### ISSUE TITLE
Simplify points notation

### ISSUE THREAD

**Issue by emersion** [mourner/rbush#36]
Now, to add a point, you have to do:

```js
tree.insert([20, 40, 20, 40]);
```

It would be simplier to do:

```js
tree.insert([20, 40]);
```

What do you think?

**Comment by mourner** [comment]
You can do this now by specifying format as `['[0]', '[1]', '[0]', '[1]']`.

**Comment by emersion** [comment]
You mean, `tree.insert([20, 40, '[0]', '[1]']);` inserts a point at 20,40?

**Comment by mourner** [comment]
No, I mean:

```js
var tree = rbush(9, ['[0]', '[1]', '[0]', '[1]']);
tree.insert([20, 40]);
```

**Comment by emersion** [comment]
Oh, thanks!
