### ISSUE TITLE
Publish to Bower

### ISSUE THREAD

**Issue by emersion** [mourner/rbush#38]
Publish this library to http://bower.io/

**Comment by mourner** [comment]
No, sorry. Just use the GitHub url https://github.com/mourner/rbush if you need.

**Comment by samehraban** [comment]
@mourner Is there any reason you don't want to publish this to bower?

**Comment by mourner** [comment]
I believe Bower is a legacy tool that no longer has a place in the JavaScript ecosystem. In addition to many other flaws like no proper dependency resolution, it greatly increases burden on open source maintainers by requiring them to commit built files to the repo, which is an anti-pattern that makes project maintenance harder, or resort to ugly and complicated hacks like tagging temporary off-branch commits with built files for releases. Please use NPM/Browserify/Webpack/JSPM/whatever and abandon Bower for good.
