### ISSUE TITLE
Object-based API

### ISSUE THREAD

**Issue by mourner** [mourner/rbush#44]
I'm considering a breaking API change that will make RBush more performant, but also more verbose, by replacing internal representation of bounding boxes from a 4-length array to a 4-property object. V8 handles object literals faster, and this also allows simplifying some internal logic. API-wise, this would look like this:

```js
// before
tree.insert([20, 40, 30, 50]);
tree.search([5, 6, 10, 12]);

// after
tree.insert({minX: 20, minY; 40, maxX: 30, maxY: 50});
tree.search({minX: 5, minY: 6, maxX: 10, maxY: 12});
```

You would still be able to configure a custom format for inserted items, but would have to change `search` to use object literals for bbox instead of arrays in any case.

The tree node JSON format would also change:

```js
// before
{
  children: [...],
  height: 1,
  bbox: [0, 0, 20, 20],
  leaf: true
}

// after
{
  children: [...],
  height: 1,
  minX: 0,
  minY: 0,
  maxX: 20,
  maxY: 20,
  leaf: true
}
```

This is implemented in `memory-perf` branch that I'm increasingly using in my new algorithmic experiments. The benchmark results (in Node 6.2.2) are as follows:

```bash
# master, items: 1000000, nodeSize: 16
insert one by one: 4969.933ms
1000 searches 10%: 2534.136ms
1000 searches 1%: 472.504ms
1000 searches 0.01%: 61.429ms
remove 1000 one by one: 26.362ms
bulk-insert 1M more: 1506.807ms
1000 searches 1%: 839.277ms
1000 searches 0.01%: 107.652ms

# memory-perf, items: 1000000, nodeSize: 16
insert one by one: 3523.986ms
1000 searches 10%: 2202.467ms
1000 searches 1%: 345.745ms
1000 searches 0.01%: 31.921ms
remove 1000 one by one: 30.391ms
bulk-insert 1M more: 1226.326ms
1000 searches 1%: 610.299ms
1000 searches 0.01%: 71.066ms
```

@twpayne @tschaub @mbloch @oscarlorentzon @vkurchatkin @bhousel — does this sound acceptable? I would bump the major version for this of course.

**Comment by IvanSanchez** [comment]
@mourner I've tried to run the perf tests on FFX 46 (using the `memory-perf` branch @760a69b), but got the following error:

```
TypeError: node is undefined
rbush.prototype._chooseSubtree() rbush.js:265
rbush.prototype._insert() rbush.js:302
rbush.prototype.insert() rbush.js:124
<anonymous> perf.js:37
```

It also seems to fail in the same fashion on Node v4.4.3:

```
TypeError: Cannot read property 'leaf' of undefined 
    at Object.rbush._chooseSubtree (/home/ivan/devel/rbush/rbush.js:265:21)
    at Object.rbush._insert (/home/ivan/devel/rbush/rbush.js:302:25)   
    at Object.rbush.insert (/home/ivan/devel/rbush/rbush.js:124:24)    
    at Object.<anonymous> (/home/ivan/devel/rbush/bench/perf.js:37:10)        
```

**Comment by mourner** [comment]
The latest commit in #45 should make insertion 10% faster on top of this. So looks like the change is definitely worth breaking the API.

**Comment by bhousel** [comment]
That sounds great!  nice find..

**Comment by vkurchatkin** [comment]
Amazing results! API change looks good to me

**Comment by oscarlorentzon** [comment]
Great! API change is fine.

**Comment by bryevdv** [comment]
+1 I would update the version Bokeh uses for sure.
