### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by siddhupiddu** [mourner/rbush#50]
Is the time complelxity of search and insert close to log n ? 

Is it better to give the max number of points in constructor than to not provide

**Comment by mourner** [comment]
It's `O(log n)` average for both insertion and search (but depends on the size of the bounding box relative to the whole space). Max node size is `9` by default and it's a reasonable choice that works well in most cases. You can experiment with increasing it though. The best values are squared — e.g. 9, 16, 25, 36, 49, 64 etc.
