### ISSUE TITLE
adding points after the new breaking change

### ISSUE THREAD

**Issue by siddhupiddu** [mourner/rbush#51]
The update says:

Breaking: changed the default format of inserted items from [20, 40, 30, 50] to {minX: 20, minY: 40, maxX: 30, maxY: 50}.

Does this mean we cannot add points now but only rectangles?  Can we add a point by putting minX = maxX ?

**Comment by mourner** [comment]
You can do everything you could before. The docs even includes an example for array-like points https://github.com/mourner/rbush#data-format
