### ISSUE TITLE
Update bower

### ISSUE THREAD

**Issue by mortzdk** [mourner/rbush#60]
Hey.

First of all, this is a very nice project!

One thing I noted was the fact that the latest version available on bower is several versions behind this repository. This should be updated since a lot of nice feature, tweaks etc. have been made since version 1.3.5 available on bower.

/ Morten

**Comment by mourner** [comment]
This repository has never been published on Bower officially, and maintainers don't have a plan to do so. Please use a modern package manager like NPM or Yarn instead.
