### ISSUE TITLE
Feature request: longitude-safe

### ISSUE THREAD

**Issue by kkdd** [mourner/rbush#75]
Hello,
I would like to use a query rectangle over the antimeridian as shown in the following example:
![globe](https://cloud.githubusercontent.com/assets/5372642/26671200/981407fa-46ef-11e7-8bfd-0be56ce1b2e7.jpg)

- ref. [Geographic Bounding Boxes](https://www.jasondavies.com/maps/bounds/) by Jason Davies

**Comment by mourner** [comment]
Just do two adjacent queries, and deduplicate the results that cross the dateline. I have no plans to implement dateline handling in rbush itself since it's a generic (not geo-specific) library, but I might release an rbush plugin for geo handling some time this year.

**Comment by kkdd** [comment]
Thank you for explanation. I'm looking forward to your geo-handling plugin.
