### ISSUE TITLE
Custom element support

### ISSUE THREAD

**Issue by mudi77** [mourner/rbush#81]
Hi,

I was glad that I found this powerful and tiny library and from beginning I relied on this statement or feature :  "var tree = rbush(9, ['[0]', '[1]', '[0]', '[1]']);"   - to incorporate custom element defined by svg paths 

so I put together some local test but seems it is not working as I expected - my output from collide detection looks like element is always evaluated as rectangle. Is it expected behavior or am I doing something wrong ? does this algorithm support searching for custom elements let say irregular polygon?

Thank You
BR

**Comment by photonstorm** [comment]
While an R-tree data structure _could_ be used for polygons, rbush only supports points and rectangles. To be fair to the author, it does state this several times in the readme!

**Comment by mourner** [comment]
Yes, R-tree is a data structure that can only incorporate rectangles and points. For most cases, it's enough to calculate a bounding box of your line/polygon and use that for indexing.
