### ISSUE TITLE
Convert to an ES6 module?

### ISSUE THREAD

**Issue by rowanwins** [mourner/rbush#88]
Hi @mourner

Just wondering if you're open to converting this to an ES6 module as per the approach you've taken with [quickselect](https://github.com/mourner/quickselect). 

If you are happy I'm willing to put together the pull request.

Thanks,
Rowan

**Comment by larsgk** [comment]
That would be awesome - especially if it fixes the ES6 issue here: https://github.com/Polymer/tools/issues/608 mentioning https://github.com/openlayers/openlayers/issues/7766
