### ISSUE TITLE
Search/collision "intersects" also triggers on "contains"?

### ISSUE THREAD

**Issue by danielsedlacek** [mourner/rbush#90]
Hi Vladimir, first of all, this is awesome, thanks!

I am not a native speaker and I would like to clarify if the search/collision methods trigger when one square fully contains smaller square even if they technically do not intersect.

For instance, do squares [0,0,100,100] and [10,10,90,90] intersect?

Thanks!

**Comment by mourner** [comment]
The outlines of the boxes don't intersect, but the boxes themselves (with their interior) do.
